baseURL = "mrsnailo.github.io/website"
title = "Shahid parvez"
theme = "github.com/razonyang/hugo-theme-bootstrap"
copyright = "Copyright © 2016-{year} Shahid parvez. All Rights Reserved."
defaultContentLanguage = "en"
paginate = 10
enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true

[blackfriday]
hrefTargetBlank = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
authors = "authors"

[build]
writeStats = true

[permalinks]
news = "/news/:year/:month/:title/"

